"""Application constants."""

# Decision enums
DECISION_APPROVE = "approve"
DECISION_REJECT = "reject"
DECISION_MANUAL_REVIEW = "manual_review"

# Agent-specific aliases
AGENT_DECISION_APPROVE = DECISION_APPROVE
AGENT_DECISION_REJECT = DECISION_REJECT
AGENT_DECISION_MANUAL_REVIEW = DECISION_MANUAL_REVIEW

DECISION_SOURCES = {"rule_engine", "llm", "fallback"}
DECISIONS = {DECISION_APPROVE, DECISION_REJECT, DECISION_MANUAL_REVIEW}

# Agent keys
AGENT_PRODUCT_REVIEW = "shop_product_review"
AGENT_COMMENT_REVIEW = "shop_comment_review"
AGENT_IMAGE_REVIEW = "image_review"
AGENT_BUY_REQUEST_REVIEW = "buy_request_review"
AGENT_CHAT_PATROL = "chat_patrol"
AGENT_OPS_COPILOT = "ops_copilot"
AGENT_DECISION_ADVISOR = "decision_advisor"

ALL_AGENT_KEYS = [
    AGENT_PRODUCT_REVIEW,
    AGENT_COMMENT_REVIEW,
    AGENT_IMAGE_REVIEW,
    AGENT_BUY_REQUEST_REVIEW,
    AGENT_CHAT_PATROL,
    AGENT_OPS_COPILOT,
    AGENT_DECISION_ADVISOR,
]

# Permission actions
ACTION_VIEW = "view"
ACTION_EDIT = "edit"
ACTION_DELETE = "delete"

# Module names
MODULE_DASHBOARD = "dashboard"
MODULE_USERS = "users"
MODULE_SUSPICIOUS = "suspicious"
MODULE_CLIENT_SETTINGS = "client_settings"
MODULE_BACKUPS = "backups"
MODULE_AUDIT = "audit"
MODULE_TOOLS = "tools"
MODULE_TICKETS = "tickets"
MODULE_SHOP = "shop"
MODULE_IMAGE = "image"
MODULE_SUB_ADMINS = "sub_admins"
